include("error.jl")
include("ast_def.jl")
include("ctx_def.jl")
include("alphalib.jl")
include("ast.jl")
include("ctx.jl")
include("semantics.jl")
include("codegen.jl")
include("cli.jl")

# Generated by parser.syntax
include("parser.yy.jl")

alphamain() = climain(ARGS)
